language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"


env:
  - TOX_VERSION="tox>=3.0,<3.1"
  - TOX_VERSION="tox>=3.1,<3.2"
  - TOX_VERSION="tox>=3.2,<3.3"
  - TOX_VERSION="tox>=3.3,<3.4"
  - TOX_VERSION="tox>=3.4,<3.5"
  - TOX_VERSION="tox>=3.8,<3.9"
  - TOX_VERSION="tox>=3.9,<3.10"
  - TOX_VERSION="tox>=3.10,<3.11"
  - TOX_VERSION="tox>=3.11,<3.12"
  - TOX_VERSION="tox>=3.12,<3.13"
  - TOX_VERSION="tox>=3.13,<3.14"
  - TOX_VERSION="tox>=3.14,<3.15"
  - TOX_VERSION="tox>=3.15,<3.16"
  - TOX_VERSION="tox>=3.16,<3.17"
  - TOX_VERSION="tox>=3.17,<3.18"
  - TOX_VERSION="tox>=3.18,<3.19"
  - TOX_VERSION="tox>=3.19,<3.20"
  - TOX_VERSION="tox>=3.20,<3.21"

install:
  - pip install ${TOX_VERSION} tox-travis codecov

script:
  - tox

after_success:
  - codecov
