# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Package Compatibility

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.8]
        tox-version: [
          "3.12.1", 
          "3.13.2", 
          "3.14.6", 
          "3.15.2", 
          "3.16.0", 
          "3.17.1", 
          "3.18.0", 
          "3.19.0", 
          "3.20.0"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox==${{ matrix.tox-version }} tox-gh-actions codecov
        pip install -r requirements.txt
    - name: Test with tox
      run: |
        tox 
